### ISSUE TITLE
New test cases: all zeroes, negative values in sequence

### ISSUE THREAD

**Issue by i-n-samartsev** [EvgenyBelichkov/EPAM_HW#2]
https://github.com/EvgenyBelichkov/EPAM_HW/blob/485d374c6e817802a5a9d6d3ab45307c669d70f1/homework1/task02/tests/test_Fibonacci.py#L13

please add checks that checks if the the following are  proper sequences or not:
(0,0,0,0,)
(-2, -3, -5, -8, -11,...)

**Comment by EvgenyBelichkov** [comment]
According to issue I added additional zeros and negative values in test file in task 02, improved code. All information in pool request "Added zeros and negative values in test sequence in task 02, improved… #7". I would be glad to get your feedback.
Thank you in advance.
